# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'labpsu.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_main_window(object):
    def setupUi(self, main_window):
        main_window.setObjectName("main_window")
        main_window.resize(452, 238)
        main_window.setWindowTitle("Power Supply")
        self.main_widget = QtWidgets.QWidget(main_window)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.main_widget.sizePolicy().hasHeightForWidth())
        self.main_widget.setSizePolicy(sizePolicy)
        self.main_widget.setObjectName("main_widget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.main_widget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.main_layout = QtWidgets.QGridLayout()
        self.main_layout.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.main_layout.setObjectName("main_layout")
        self.line_4 = QtWidgets.QFrame(self.main_widget)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.main_layout.addWidget(self.line_4, 6, 0, 1, 3)
        self.line_2 = QtWidgets.QFrame(self.main_widget)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.main_layout.addWidget(self.line_2, 2, 0, 1, 3)
        self.current_apply_layout = QtWidgets.QVBoxLayout()
        self.current_apply_layout.setObjectName("current_apply_layout")
        self.current_apply_button = QtWidgets.QPushButton(self.main_widget)
        self.current_apply_button.setObjectName("current_apply_button")
        self.current_apply_layout.addWidget(self.current_apply_button)
        spacerItem = QtWidgets.QSpacerItem(10, 16, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.current_apply_layout.addItem(spacerItem)
        self.main_layout.addLayout(self.current_apply_layout, 5, 2, 1, 1)
        self.voltage_apply_layout = QtWidgets.QVBoxLayout()
        self.voltage_apply_layout.setObjectName("voltage_apply_layout")
        self.voltage_apply_button = QtWidgets.QPushButton(self.main_widget)
        self.voltage_apply_button.setObjectName("voltage_apply_button")
        self.voltage_apply_layout.addWidget(self.voltage_apply_button)
        spacerItem1 = QtWidgets.QSpacerItem(10, 18, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.voltage_apply_layout.addItem(spacerItem1)
        self.main_layout.addLayout(self.voltage_apply_layout, 3, 2, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 18, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.main_layout.addItem(spacerItem2, 8, 1, 1, 1)
        self.current_label_layout = QtWidgets.QVBoxLayout()
        self.current_label_layout.setObjectName("current_label_layout")
        self.current_label = QtWidgets.QLabel(self.main_widget)
        self.current_label.setObjectName("current_label")
        self.current_label_layout.addWidget(self.current_label)
        spacerItem3 = QtWidgets.QSpacerItem(10, 16, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.current_label_layout.addItem(spacerItem3)
        self.main_layout.addLayout(self.current_label_layout, 5, 0, 1, 1)
        self.output_button = QtWidgets.QPushButton(self.main_widget)
        self.output_button.setObjectName("output_button")
        self.main_layout.addWidget(self.output_button, 7, 2, 1, 1)
        self.serial_port_connect_button = QtWidgets.QPushButton(self.main_widget)
        self.serial_port_connect_button.setAutoDefault(False)
        self.serial_port_connect_button.setFlat(False)
        self.serial_port_connect_button.setObjectName("serial_port_connect_button")
        self.main_layout.addWidget(self.serial_port_connect_button, 0, 2, 1, 1)
        self.output_label = QtWidgets.QLabel(self.main_widget)
        self.output_label.setObjectName("output_label")
        self.main_layout.addWidget(self.output_label, 7, 0, 1, 1)
        self.voltage_label_layout = QtWidgets.QVBoxLayout()
        self.voltage_label_layout.setObjectName("voltage_label_layout")
        self.voltage_label = QtWidgets.QLabel(self.main_widget)
        self.voltage_label.setObjectName("voltage_label")
        self.voltage_label_layout.addWidget(self.voltage_label)
        spacerItem4 = QtWidgets.QSpacerItem(10, 18, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.voltage_label_layout.addItem(spacerItem4)
        self.main_layout.addLayout(self.voltage_label_layout, 3, 0, 1, 1)
        self.serial_port_input = QtWidgets.QLineEdit(self.main_widget)
        self.serial_port_input.setStyleSheet("")
        self.serial_port_input.setObjectName("serial_port_input")
        self.main_layout.addWidget(self.serial_port_input, 0, 1, 1, 1)
        self.current_layout = QtWidgets.QVBoxLayout()
        self.current_layout.setObjectName("current_layout")
        self.current_input = QtWidgets.QDoubleSpinBox(self.main_widget)
        self.current_input.setDecimals(3)
        self.current_input.setMaximum(3.2)
        self.current_input.setSingleStep(0.2)
        self.current_input.setProperty("value", 1.0)
        self.current_input.setObjectName("current_input")
        self.current_layout.addWidget(self.current_input)
        self.current_indicator = QtWidgets.QProgressBar(self.main_widget)
        self.current_indicator.setMaximumSize(QtCore.QSize(16777215, 16))
        self.current_indicator.setMaximum(1000)
        self.current_indicator.setProperty("value", 0)
        self.current_indicator.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.current_indicator.setTextVisible(True)
        self.current_indicator.setOrientation(QtCore.Qt.Horizontal)
        self.current_indicator.setInvertedAppearance(False)
        self.current_indicator.setTextDirection(QtWidgets.QProgressBar.TopToBottom)
        self.current_indicator.setFormat("%v mA")
        self.current_indicator.setObjectName("current_indicator")
        self.current_layout.addWidget(self.current_indicator)
        self.main_layout.addLayout(self.current_layout, 5, 1, 1, 1)
        self.voltage_layout = QtWidgets.QVBoxLayout()
        self.voltage_layout.setObjectName("voltage_layout")
        self.voltage_input = QtWidgets.QDoubleSpinBox(self.main_widget)
        self.voltage_input.setDecimals(3)
        self.voltage_input.setMaximum(36.0)
        self.voltage_input.setSingleStep(0.2)
        self.voltage_input.setProperty("value", 5.0)
        self.voltage_input.setObjectName("voltage_input")
        self.voltage_layout.addWidget(self.voltage_input)
        self.voltage_indicator = QtWidgets.QPushButton(self.main_widget)
        self.voltage_indicator.setEnabled(True)
        self.voltage_indicator.setMaximumSize(QtCore.QSize(16777215, 18))
        self.voltage_indicator.setObjectName("voltage_indicator")
        self.voltage_layout.addWidget(self.voltage_indicator)
        self.main_layout.addLayout(self.voltage_layout, 3, 1, 1, 1)
        self.serial_port_label = QtWidgets.QLabel(self.main_widget)
        self.serial_port_label.setObjectName("serial_port_label")
        self.main_layout.addWidget(self.serial_port_label, 0, 0, 1, 1)
        self.line_1 = QtWidgets.QFrame(self.main_widget)
        self.line_1.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_1.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_1.setObjectName("line_1")
        self.main_layout.addWidget(self.line_1, 1, 0, 1, 3)
        self.line_3 = QtWidgets.QFrame(self.main_widget)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.main_layout.addWidget(self.line_3, 4, 0, 1, 3)
        self.gridLayout_2.addLayout(self.main_layout, 0, 0, 1, 1)
        main_window.setCentralWidget(self.main_widget)
        self.current_label.setBuddy(self.current_input)
        self.output_label.setBuddy(self.output_button)
        self.voltage_label.setBuddy(self.voltage_input)
        self.serial_port_label.setBuddy(self.serial_port_input)

        self.retranslateUi(main_window)
        self.serial_port_input.returnPressed.connect(self.serial_port_connect_button.click)
        QtCore.QMetaObject.connectSlotsByName(main_window)
        main_window.setTabOrder(self.serial_port_input, self.serial_port_connect_button)
        main_window.setTabOrder(self.serial_port_connect_button, self.voltage_input)
        main_window.setTabOrder(self.voltage_input, self.voltage_apply_button)
        main_window.setTabOrder(self.voltage_apply_button, self.current_input)
        main_window.setTabOrder(self.current_input, self.current_apply_button)
        main_window.setTabOrder(self.current_apply_button, self.output_button)
        main_window.setTabOrder(self.output_button, self.voltage_indicator)

    def retranslateUi(self, main_window):
        _translate = QtCore.QCoreApplication.translate
        self.current_apply_button.setText(_translate("main_window", "Set"))
        self.voltage_apply_button.setText(_translate("main_window", "Set"))
        self.current_label.setText(_translate("main_window", "Current:"))
        self.output_button.setText(_translate("main_window", "Enable"))
        self.serial_port_connect_button.setText(_translate("main_window", "Connect"))
        self.output_label.setText(_translate("main_window", "Output:"))
        self.voltage_label.setText(_translate("main_window", "Voltage:"))
        self.serial_port_input.setText(_translate("main_window", "/dev/ttyUSB0"))
        self.current_input.setSuffix(_translate("main_window", " A"))
        self.voltage_input.setSuffix(_translate("main_window", " V"))
        self.voltage_indicator.setText(_translate("main_window", "0 mV"))
        self.serial_port_label.setText(_translate("main_window", "Serial port:"))

